test: &default

  # Credentials for REST APIs
  # client_id: AQcD9Kxsxav_nifTkgLzOV3f6IMVzsyDLBGiogWYscHVcO6Mb9k9tc_Z-Yt64V64axGiQ8L8ogNeO-lB
  # client_secret: EOXgGANh8cm6AFhPihAmIBSruja78qvgfr84YFT-f3zFTsa5g-pOqeczfoXcZ-sxrua5XVdmyGo5TfuM

  client_id: AT8xxgfod-fiT4SeSjuKkluKIdTwisWWkhsEjjY2HFSfjkhVJYttPYqJa6EeCC_KTZai_NBVmSk9MBwv
  client_secret: EBMhodcppnikvMxTOxKgH_m3pxchGm_vVOohnr4QFEi8oQoko67TzOtHGbQbDWzMAWU7pCX63PtX5so2
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: ya1000e_facilitator@gmail.com
  http_timeout: 90000
  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
